#Pre-processing and Training:



In [3]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
import string

In [4]:
df = pd.read_csv('train.csv')
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [5]:
df.shape

(2225, 2)

In [6]:
df['category'].value_counts()

sport            511
business         510
politics         417
tech             401
entertainment    386
Name: category, dtype: int64

In [7]:
import nltk
nltk.download('stopwords')
from nltk import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [9]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))

In [10]:
def text_cleaning(a):
 remove_punctuation = [char for char in a if char not in string.punctuation]
 #print(remove_punctuation)
 remove_punctuation=''.join(remove_punctuation)
 #print(remove_punctuation)
 return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words('english')]

In [14]:
# df=df.iloc[:,1].apply(text_cleaning)

In [15]:
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_cleaning).fit(df['text'])

# print(len(bow_transformer.vocabulary_))
# bow_transformer.vocabulary_

In [17]:
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [ ]:
title_bow = bow_transformer.transform(df['text'])
print(title_bow)

In [20]:
X = title_bow.toarray()
print(X)
X.shape

[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(2225, 32955)

In [ ]:
# TF-IDF Algo -term frequency-inverse document frequency to know the most significant words

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer().fit(title_bow)
print(tfidf_transformer)

title_tfidf=tfidf_transformer.transform(title_bow)
print(title_tfidf)# got tfidf values for whole vocabulary
print(title_tfidf.shape)   #(2225, 32955)

In [22]:
X=title_tfidf

In [23]:
Y=df['category']

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(2002, 32955) (2002,)
(223, 32955) (223,)


In [33]:
print(len(Y),len(Y_train),len(Y_test))

2225 2002 223


In [26]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train,Y_train)

In [27]:
all_predictions = model.predict(X_test)
print(all_predictions)

['politics' 'business' 'entertainment' 'tech' 'sport' 'business'
 'business' 'sport' 'sport' 'tech' 'entertainment' 'entertainment'
 'entertainment' 'entertainment' 'entertainment' 'tech' 'politics' 'sport'
 'entertainment' 'politics' 'entertainment' 'entertainment' 'business'
 'politics' 'politics' 'politics' 'politics' 'sport' 'entertainment'
 'sport' 'politics' 'tech' 'politics' 'entertainment' 'business'
 'entertainment' 'tech' 'business' 'tech' 'sport' 'business' 'sport'
 'entertainment' 'business' 'entertainment' 'entertainment' 'business'
 'sport' 'entertainment' 'sport' 'politics' 'sport' 'entertainment'
 'entertainment' 'entertainment' 'business' 'politics' 'business'
 'entertainment' 'business' 'entertainment' 'business' 'business'
 'business' 'politics' 'sport' 'sport' 'entertainment' 'business'
 'business' 'tech' 'business' 'tech' 'tech' 'tech' 'politics' 'tech'
 'entertainment' 'business' 'tech' 'business' 'politics' 'politics'
 'entertainment' 'politics' 'sport' 'sport' '

In [28]:
#Printing the confusion matrix of our prediction
from sklearn.metrics import confusion_matrix

confusion_matrix(Y_test, all_predictions)

array([[42,  0,  4,  0,  0],
       [ 0, 41,  0,  0,  3],
       [ 1,  0, 46,  0,  0],
       [ 0,  0,  0, 48,  0],
       [ 1,  0,  0,  1, 36]])

In [29]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, all_predictions)

print(f'Accuracy: {accuracy:.4f}')


Accuracy: 0.9552


#Testing on new data

In [34]:
df2= pd.read_csv('test.csv')

In [35]:
df2.head()

category                                               text
0  entertainment  row threatens hendrix museum plan proposals to...
1       politics  debate needed  on donations cap a cap on donat...
2       business  german growth goes into reverse germany s econ...
3       politics  labour targets  hardcore truants  a fresh crac...
4          sport  federer claims dubai crown world number one ro...

In [42]:
df2.shape

(184, 2)

In [38]:
title_bow2 = bow_transformer.transform(df2['text'])


In [39]:
title_tfidf2=tfidf_transformer.transform(title_bow2)


In [41]:
all_predictions = model.predict(title_tfidf2)
print(all_predictions,len(all_predictions))

['entertainment' 'politics' 'business' 'politics' 'sport' 'business'
 'sport' 'tech' 'entertainment' 'politics' 'politics' 'politics'
 'business' 'sport' 'politics' 'business' 'business' 'sport' 'politics'
 'business' 'sport' 'sport' 'business' 'business' 'sport' 'business'
 'sport' 'business' 'tech' 'business' 'entertainment' 'tech' 'business'
 'politics' 'business' 'politics' 'sport' 'business' 'tech' 'business'
 'sport' 'sport' 'business' 'business' 'sport' 'politics' 'business'
 'entertainment' 'politics' 'politics' 'business' 'entertainment'
 'business' 'sport' 'sport' 'politics' 'sport' 'politics' 'sport'
 'business' 'sport' 'business' 'entertainment' 'entertainment' 'sport'
 'business' 'politics' 'politics' 'tech' 'sport' 'entertainment' 'sport'
 'tech' 'business' 'entertainment' 'sport' 'entertainment' 'sport'
 'entertainment' 'entertainment' 'politics' 'sport' 'sport'
 'entertainment' 'politics' 'business' 'tech' 'business' 'business' 'tech'
 'sport' 'politics' 'sport' 'tech' 

In [45]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(df2['category'], all_predictions)

print(f'Accuracy: {accuracy:.4f}')


Accuracy: 0.9946


#Custom Example:

In [60]:
testdata=['Sports play great role in improving and maintaining the health and fitness, improving mental skills and concentration level as well as social and communication skills. Playing sports on regular basis prevents person form the many diseases and disorders of the body organs especially overweight, obese and heart problems.',
          'This can include news about upcoming movie releases, TV show premieres, album launches, celebrity events, and industry trends. Entertainment news is often covered by dedicated media outlets and is of interest to those who enjoy staying informed about the latest happenings in the entertainment industry.',
          'In a groundbreaking move for the financial sector, TechFin Ventures announced a strategic partnership with Quantum Capital, aiming to revolutionize investment strategies. The collaboration leverages cutting-edge artificial intelligence and blockchain technologies to create innovative financial solutions. Industry experts anticipate this synergy to redefine the landscape of asset management, enhancing both efficiency and transparency.',
          'In an electrifying turn of events, Stellar Studios unveiled plans for a blockbuster collaboration between two iconic actors, Emily Starlight and Jackson Dynamo. The star-studded duo is set to headline a futuristic sci-fi thriller, "Cosmic Convergence," directed by the visionary filmmaker, Luna Spectra. The film promises a cinematic spectacle, blending state-of-the-art visual effects with a gripping narrative that transcends the boundaries of imagination. Industry insiders speculate that Cosmic Convergence could redefine the science fiction genre',
          ]

In [61]:
title_bow3 = bow_transformer.transform(testdata)

In [62]:
title_tfidf3=tfidf_transformer.transform(title_bow3)


In [63]:
all_predictions = model.predict(title_tfidf3)
print(all_predictions,len(all_predictions))

['sport' 'tech' 'business' 'entertainment'] 4
